[Eppeta-9] Frontend Styling to Landing and Evaluation Pages
Ed-Fi-Exchange-OSS/EvaluationTracker pull request #5
Opened 2023-07-12 15:48 UTC by StevenM0

2023-07-13 20:25 UTC, stevenarnold-ed-fi requested changes

2023-07-13 20:25 UTC, stevenarnold-ed-fi commented on src/reactapp/public/index.html
> +    <title>Teacher Tracker Evaluation</title>
We may change this later but for now, change to 'Candidate Evaluation Tracker'

2023-07-19 14:38 UTC, stephenfuqua commented
@StevenM0 please rebase this branch from `main` and then force push an update back to GitHub, so that we can merge this pull request.

2023-07-19 16:47 UTC, stevenarnold-ed-fi approved these changes

2023-07-20 18:37 UTC, stephenfuqua approved these changes

2023-07-20 18:37 UTC, merged